name: rpm+goreleaser

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:

  rpmbuilder:
        name: Create RPM Release (using ubuntu, what a strange way to build RPM)
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@master

        - name: Replace version in RPM spec so correct source is downloaded when building RPM
          run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.ref_name}}/' scripts/viriumd.spec

        - name: build RPM package
          id: rpm_build
          uses: naveenrajm7/rpmbuild@master
          with:
              spec_file: "scripts/viriumd.spec"
            
        - name: Release
          uses: softprops/action-gh-release@v2
          if: github.ref_type == 'tag'
          with:
            files: |
              ${{ steps.rpm_build.outputs.source_rpm_path }}
              ${{ steps.rpm.outputs.rpm_dir_path }}/viriumd-${{github.ref_name}}-1.el9.x86_64.rpm

# **************************************************************************************************************
#       Goreleaser 
# **************************************************************************************************************

  goreleaser:
        name: Create RPM Release (using ubuntu, what a strange way to build RPM)
        runs-on: ubuntu-latest

        steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v5

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            distribution: goreleaser
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

