name: rpm+goreleaser

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:

  rpmbuilder:
        name: Create RPM Release (using ubuntu, what a strange way to build RPM)
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@master

        - name: Replace version in RPM spec so correct source is downloaded when building RPM
          run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.ref_name}}/' scripts/rpmbuild/SPECS/viriumd.spec

        - name: build RPM package
          id: rpm_build
          uses: naveenrajm7/rpmbuild@master
          with:
              spec_file: "scripts/rpmbuild/SPECS/viriumd.spec"
            
        - name: Upload .rpm package as artifact
          uses: actions/upload-artifact@v3
          with:
            name: ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
            path: rpmbuild/RPMS/${{ env.ARCH }}/*.rpm
# **************************************************************************************************************
#       Goreleaser 
# **************************************************************************************************************
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v5

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            distribution: goreleaser
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

